### ISSUE TITLE
Chapters load very slowly on ZeroNet even while they're already downloaded.

### ISSUE THREAD

**Issue by styromaniac** [PR0M3TH3AN/eternal-word#5]
https://zeronet.io/ is where you download ZeroNet. It's required for the site I link below.

The site's address: http://127.0.0.1:43110/1Mjd9zn88kNX1QEkFaq2MrWeMthnR15Fga/

I suspect it's a CSS or SCSS file or so causing the problem.

ZeroNet uses an iframe to sandbox sites, just in case it makes a difference.

BTW, you should mention ZeroNet on The Eternal Word like you do for IPFS.

**Comment by styromaniac** [comment]
Are you even alive? Hello?

**Comment by PR0M3TH3AN** [comment]
I'm not a fan of Zero-net particularly because of its blatant linking to legal and illegal adult content. With IPFS you have no such issue as IPFS is a protocol and not a platform.  Feel free to fork the project and do as you wish. IMHO ZN is more dangerous than TOR and i personally wouldn't recommend it to anyone.

**Comment by styromaniac** [comment]
Can't you add the little bit of code? I don't have the tools that you must have for changing the heads of all nearly 25K htm files at once.

**Comment by styromaniac** [comment]
BTW, I've seen that illegal porn is easy to find on IPFS and with Tor there was a social network that became a CP site, so...

And ZeroNet has blocklists. I have one without linking to the sites.

**Comment by styromaniac** [comment]
Never mind. Somehow it was slow on my laptop until I redownloaded the site following Linux Mint no longer working.
